### PR TITLE
Add include file support

### LINKED ISSUE #5: Add support for include files
Hi,
thanks, I will try it... about the multi-document.
Yes, e.g. I have a main dockument and the chapters in a subfolder
image
image
And within the text directory one could have something like:
image
So, no I would not say that all open org files is the best approach (usually I have plenty of org files open, which are not relevant for the document).

There could be a few other options:
1) one needs to define a `main`-org-file (which would be the one with the includes above), but I am not sure if the includes are recognized.
2) The  kind of (recursive) grepping takes place in all org-files in the current directory of the current file (this would work with the setup above).
3) one defines a directory where the kind of grepping taks place

Thank you very much!

_Originally posted by @fab6 in https://github.com/bdarcus/oxr/issues/3#issuecomment-1159370942_

### PR DESCRIPTION
**Pull request by bdarcus**
Closes #5

I also added a cache, but it's not actually caching ATM.

----------

Not heavily tested, but here's two equations, each from separate included files.

image

Also, this only looks at the file paths; it doesn't look at the lines and such.

cc @fab6

### CODE REVIEW

**Comment by tecosaur** [comment]
Ah, sorry to be a kill joy but how well does this work with `#+include: file::*Heading` ?

**Comment by bdarcus** [comment]
Not well at all, since I'm not even sure what that is ;-)

Is that one of those implicit headline links?

If yes, I was noting to myself earlier I should probably add this, as I
don't support it even within a single file.

**Comment by tecosaur** [comment]
Unfortunately for us :P `#+include:` is a little fancy, see https://orgmode.org/manual/Include-Files.html. I've recently had to deal with this in Org Glossary, see [org-glossary.el#L372-L449](https://github.com/tecosaur/org-glossary/blob/c520d66cd86fce4154d2dcf42c7669146425bd89/org-glossary.el#L372-L449).

**Comment by bdarcus** [comment]
Ugh.

Thanks!

**Comment by bdarcus** [comment]
I wonder if it would be feasible for org to handle some of this transparently?

Like, say, an argument on org-element-parse-buffer to handle includes?

**Comment by tecosaur** [comment]
The `#+include` expansion is currently a not-nice 150-line function. I have a patch in progress to break it up, which I think should replace ` org-glossary--parse-include-value` at least. Alternatively, if you don't care about caching you can just copy the buffer content and call `org-export-expand-include-keyword`.

**Comment by fab6** [comment]
thanks, sorry, I was not aware of the details here

**Comment by bdarcus** [comment]
> thanks, sorry, I was not aware of the details here

No problem.

It will just take a bit longer to improve this.

**Comment by bdarcus** [comment]
I'm wondering again about overlap with `org-glossary`. Like aside from cross-references  benefiting from a dedicated UI and entry command (`oxr-insert-ref`), otherwise the plumbing would seem to work for this, without me needing to write or copy chunks of your code?

At a high level, both use cases involve parsing org buffers and returning in-document key-value targets.

Is that crazy @tecosaur?

**Comment by tecosaur** [comment]
Hmmm, I could envisage an extension to `org-glossary` for dynamically generated sections, e.g. all figures and references to them, etc.

I'm not sure how that would be worked in, but if it was I could see `oxr`'s functionality being folded in as part of that.

**Comment by bdarcus** [comment]
I'm not sure on the details either, but thought it worth planting the question.

It might be the parsing stuff could be part of a more general package (or more likely and ultimately code in org) and that both glossaries and cross-references use that?

**Comment by tecosaur** [comment]
That was another thought which occurred to me too. I think there's *something* here, though I'm not sure quite what yet.

**Pull request merged**
