### PR TITLE
Add equation support

### LINKED ISSUE #3: equations and multiple documents
Hi,
I just was pointed to your package :-)
It seems that it does not work for equations yet, is it planned to include? E.g. I have a latex equation like
```
\begin{equation}
\label{eqn:strange-equation}
a = \frac{10}{10} \omega_{\r{10}} + \ch{10} +\SI{01}{\m}
\end{equation}
```
And are there any plannings that it works across multiple org files? This would be great!
Best
Fab

### PR DESCRIPTION
**Pull request by bdarcus**
This source:

```elisp
#+name: eqn-1
#+caption: an equation caption
\begin{equation}
    f(x) =  \sum\limits_0^\infty(f^{(n)}(x)|_{x=0} \cdot x)
\end{equation}
```

.... results in this:

image

Close #3

-----------

@fab6 - what should it insert in the org buffer if you select this?

Right now it inserts this, which is default:

```
 [[eqn-1]]
```

I also added `oxr-insert-equation`.

### CODE REVIEW

**Comment by bdarcus** [comment]
I merged this. Give a try @fab6, and let me know if that works.

**Comment by fab6** [comment]
Hi, thank you!
This works!
image
image

which then gets translated to tex like this for me
image

When inserting, it works as well
image

though the caption would not be needed (but I just see that this could be of help when filtering) and the internal label (inside the equation) is not needed.
So this 
image
is too much.

Thanks again!

**Comment by bdarcus** [comment]
> though the caption would not be needed (but I just see that this could be of help when filtering) and the internal label (inside the equation) is not needed.

OK, I removed the latter.

**Comment by fab6** [comment]
Thanks!

**Pull request merged**
